apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-test
  template:
    metadata:
      labels:
        app: cicd-test
    spec:
      containers:
      - name: web
        image: axanth/cicd-test:latest
        ports:
        - containerPort: 80