apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-test-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: axanth.gr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicd-test-service
            port:
              number: 80
  tls:
  - hosts:
    - axanth.gr
    secretName: cicd-test-tls