apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: index-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.axanth.gr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: index-service
            port:
              number: 80
